DROP TABLE IF EXISTS `config_descriptions`;
CREATE TABLE `config_descriptions` (
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `description` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `config_descriptions` VALUES ('ActivateWeather', 'Activate weather system\r\nDefault: 1 (true)\r\n         0 (false)');
INSERT INTO `config_descriptions` VALUES ('AddonChannel', 'Permit/disable the use of the addon channel through the server\r\n(some client side addons can stop work correctly with disabled addon channel)\r\nDefault: 1 (permit addon channel)\r\n         0 (do not permit addon channel)');
INSERT INTO `config_descriptions` VALUES ('AllFlightPaths', 'Players will start with all flight paths (Note: ALL flight paths, not only player\'s team)\r\nDefault: 0 (true)\r\n         1 (false)');
INSERT INTO `config_descriptions` VALUES ('AllowTwoSide.Accounts', 'Allow accounts to create characters in both teams in any game type.\r\nDefault: 0 (Not allowed)\r\n         1 (Allowed)');
INSERT INTO `config_descriptions` VALUES ('AllowTwoSide.AddFriend', 'Allow adding friends from other team in friend list.\r\nDefault: 0 (Not allowed)\r\n         1 (Allowed)');
INSERT INTO `config_descriptions` VALUES ('AllowTwoSide.Interaction.Auction', 'Merge horde and alliance aution houses\r\nDefault: 0 (Disabled)\r\n         1 (Enabled)');
INSERT INTO `config_descriptions` VALUES ('AllowTwoSide.Interaction.Channel', 'Merge chat channels for both teams\r\nDefault: 0 (Enabled)\r\n         1 (Disabled)');
INSERT INTO `config_descriptions` VALUES ('AllowTwoSide.Interaction.Chat', 'Allow people to chat with eachother across teams\r\nDefault: 0 (Not allowed)\r\n         1 (Allowed)');
INSERT INTO `config_descriptions` VALUES ('AllowTwoSide.Interaction.Group', 'Allow different teams to be in groups with eachother\r\nDefault: 0 (Not allowed)\r\n         1 (Allowed)');
INSERT INTO `config_descriptions` VALUES ('AllowTwoSide.Interaction.Guild', 'Allow horde and alliance to be in the same guild\r\nDefault: 0 (Not allowed)\r\n         1 (Allowed)');
INSERT INTO `config_descriptions` VALUES ('AllowTwoSide.Interaction.Mail', 'Allow mailing between horde and alliance\r\nDefault: 0 (Not allowed)\r\n         1 (Allowed)');
INSERT INTO `config_descriptions` VALUES ('AllowTwoSide.WhoList', 'Enable horde and alliance to see eachother on who list\r\nDefault: 0 (Disabled)\r\n         1 (Enabled)');
INSERT INTO `config_descriptions` VALUES ('AlwaysMaxSkillForLevel', 'Players will automatically gain max level dependent (weapon/defense) skill when logging in, leveling up etc\r\nDefault: 0 (false)\r\n         1 (true)');
INSERT INTO `config_descriptions` VALUES ('AntiCheat.SpeedCheckTolerance', 'How many % overtravel is allowed\r\nDefault: 1   - 1% overtravel allowed\r\n         0   - Will fail a lot');
INSERT INTO `config_descriptions` VALUES ('Arena.ArenaSeason.ID', 'Current area season id, used for selection some rated arena settings.\r\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('Arena.AutoDistributeInterval', 'How often should the distribution take place\nIf automatic distribution is enabled in days\nDefault: 7 (weekly)');
INSERT INTO `config_descriptions` VALUES ('Arena.AutoDistributePoints', 'Set if arena points should be distributed automatically, or by GM command\nDefault: 0 (disable) (recommended): use gm command or sql query to distribute the points\n         1 (enable)  arena points are distributed automatically');
INSERT INTO `config_descriptions` VALUES ('Arena.MaxRatingDifference', 'The maximum rating difference between two groups in rated matches\nDefault: 0 (disable, rating difference is discarded)');
INSERT INTO `config_descriptions` VALUES ('Arena.QueueAnnouncer.Exit', 'Enable arena queue announcer posting to chat at exit\nDefault: 0 (disable)\n         1 (enable)');
INSERT INTO `config_descriptions` VALUES ('Arena.QueueAnnouncer.Join', 'Enable arena queue announcer posting to chat at join\nDefault: 0 (disable)\n         1 (enable)');
INSERT INTO `config_descriptions` VALUES ('Arena.RatingDiscardTimer', 'After the specified milliseconds has passed,\nrating information will be discarded when selecting teams for matches\nalso initiates an update by this timer\nDefault: 600000 (10 minutes, recommended)\n         0 (disable)');
INSERT INTO `config_descriptions` VALUES ('Arena.StartPersonalRating', 'Default Personal Rating at team creation\nDefault: -1 (use season dependent default value)');
INSERT INTO `config_descriptions` VALUES ('Arena.StartRating', 'Default Rating at team creation\nDefault: -1 (use season dependent default value)');
INSERT INTO `config_descriptions` VALUES ('Auction.Deposit.Min', 'Minimum auction deposit size in copper\nDefault: 0');
INSERT INTO `config_descriptions` VALUES ('Battleground.CastDeserter', 'Cast Deserter spell at player who leave battleground in progress\nDefault: 1 (enable)\n         0 (disable)');
INSERT INTO `config_descriptions` VALUES ('Battleground.InvitationType', 'Set Battleground invitation type\nDefault: 0 (normal - invite as much players to bg as possible, don\'t bother with ballance)\n         1 (Experimental - don\'t allow to invite much more players of one faction)');
INSERT INTO `config_descriptions` VALUES ('BattleGround.PremadeGroupWaitForMatch', 'The time in which premade group of 1 faction waits in BG Queue for premade group of other faction\nDefault: 1800000 (30 minutes)\n         0 - disable premade group matches (group always added to bg team in normal way)');
INSERT INTO `config_descriptions` VALUES ('BattleGround.PrematureFinishTimer', 'The time to end the bg if there are less than MinPlayersPerTeam on one side in milliseconds\nDefault: 300000 (5 minutes)\n         0 - disable (not recommended)');
INSERT INTO `config_descriptions` VALUES ('Battleground.QueueAnnouncer.Join', 'Enable queue announcer posting to chat at join\nDefault: 0 (not send)\n         1 (send to joined player only)\n         2 (send to all players)');
INSERT INTO `config_descriptions` VALUES ('Battleground.QueueAnnouncer.Start', 'Enable queue announcer posting to chat at BG start\nDefault: 0 (disable)\n         1 (enable)');
INSERT INTO `config_descriptions` VALUES ('BeepAtStart', 'Beep at mangosd start finished\nDefault: 1 (true)\n         0 (false)');
INSERT INTO `config_descriptions` VALUES ('CastUnstuck', 'Allow cast Unstuck spell at .start or client Help option use\nDefault: 1 (true)\n         0 (false)');
INSERT INTO `config_descriptions` VALUES ('ChangeWeatherInterval', 'Weather update interval (in milliseconds)\nDefault: 600000 (10 min)');
INSERT INTO `config_descriptions` VALUES ('Channel.RestrictedLfg', 'Restrict use LookupForGroup channel only registered in LFG tool players\nDefault: 1 (allow join to channel only if active in LFG)\n         0 (allow join to channel in any time)');
INSERT INTO `config_descriptions` VALUES ('Channel.SilentlyGMJoin', 'Silently join GM characters (security level > 1) to channels\nDefault: 0 (join announcement in normal way)\n         1 (GM join without announcement)');
INSERT INTO `config_descriptions` VALUES ('CharactersCreatingDisabled', 'Disable characters creating for specific team or any (non-player accounts not affected)\nDefault: 0 - enabled\n         1 - disabled only for Alliance\n         2 - disabled only for Horde\n         3 - disabled for both teams');
INSERT INTO `config_descriptions` VALUES ('CharactersPerAccount', 'Limit numbers of characters per account (at all realms).\nNote: this setting limits the character creating at the _current_ realm base at characters amount at all realms\nDefault: 50\n        The number must be >= CharactersPerRealm');
INSERT INTO `config_descriptions` VALUES ('CharactersPerRealm', 'Limit numbers of characters for account at realm\nDefault: 10 (client limitation)\n        The number must be between 1 and 10');
INSERT INTO `config_descriptions` VALUES ('CharDelete.KeepDays', 'Define the amount of days for which the characters are kept in the database before\nthey will be removed\nDefault: 30\n         0  - Don\'t delete any characters, they stay in the database forever.');
INSERT INTO `config_descriptions` VALUES ('CharDelete.Method', 'Character deletion behavior\nDefault: 0  - Completely remove the character from the database\n         1  - Unlinking, the character gets unlinked from the account,\n              the name gets freed up and appears as deleted ingame');
INSERT INTO `config_descriptions` VALUES ('CharDelete.MinLevel', 'Character gets deleted by CharDelete.Method=0 when the character\nhasn\'t the specified level yet.\nDefault: 0  - For all characters the specified mode will be used\n         1+ - Only for players which have reached the specified level\n              will be d');
INSERT INTO `config_descriptions` VALUES ('ChatFakeMessagePreventing', 'Chat protection from creating fake messages using a lot spaces (other invisible symbols),\nnot applied to addon language messages, but can prevent working old addons\nthat use normal languages for sending data to another clients.\nDefault: 0 (disable fake me');
INSERT INTO `config_descriptions` VALUES ('ChatFlood.MessageCount', 'Chat anti-flood protection, haste message count to activate protection\nDefault: 10\n         0 (disable anti-flood protection)');
INSERT INTO `config_descriptions` VALUES ('ChatFlood.MessageDelay', 'Chat anti-flood protection, minimum message delay to count message\nDefault: 1 (in secs)');
INSERT INTO `config_descriptions` VALUES ('ChatFlood.MuteTime', 'Chat anti-flood protection, mute time at activation flood protection (not saved)\nDefault: 10 (in secs)');
INSERT INTO `config_descriptions` VALUES ('ChatStrictLinkChecking.Kick', 'Defines, what should be done if a message is considered to contain invalid pipe commands.\nDefault: 0 (silently ignore message)\n         1 (kick players who sent invalid formed messages)');
INSERT INTO `config_descriptions` VALUES ('ChatStrictLinkChecking.Severity', 'Check chat messages for ingame links to spells, items, quests, achievements etc.\nDefault: 0 (disable link checking)\n         1 (check if only valid pipe commands are used. This prevents posting pictures for example)\n         2 (verifiy that pipe commands ');
INSERT INTO `config_descriptions` VALUES ('CleanCharacterDB', 'Perform character db cleanups on start up\nDefault: 1 (Enable)\n         0 (Disabled)');
INSERT INTO `config_descriptions` VALUES ('Compression', 'Compression level for update packages sent to client (1..9)\nDefault: 1 (speed)\n         9 (best compression)');
INSERT INTO `config_descriptions` VALUES ('ConfVersion', 'Config version');
INSERT INTO `config_descriptions` VALUES ('Console.Enable', 'Enable console\nDefault: 1 - on\n         0 - off');
INSERT INTO `config_descriptions` VALUES ('Corpse.Decay.ELITE', 'Seconds until creature corpse will decay without being looted or skinned (not used when creature does not have loot initially)\nDefault: 300, 900, 600, 1200, 3600');
INSERT INTO `config_descriptions` VALUES ('Corpse.Decay.NORMAL', 'Seconds until creature corpse will decay without being looted or skinned (not used when creature does not have loot initially)\r\nDefault: 300, 900, 600, 1200, 3600');
INSERT INTO `config_descriptions` VALUES ('Corpse.Decay.RARE', 'Seconds until creature corpse will decay without being looted or skinned (not used when creature does not have loot initially)\nDefault: 300, 900, 600, 1200, 3600');
INSERT INTO `config_descriptions` VALUES ('Corpse.Decay.RAREELITE', 'Seconds until creature corpse will decay without being looted or skinned (not used when creature does not have loot initially)\nDefault: 300, 900, 600, 1200, 3600');
INSERT INTO `config_descriptions` VALUES ('Corpse.Decay.WORLDBOSS', 'Seconds until creature corpse will decay without being looted or skinned (not used when creature does not have loot initially)\nDefault: 300, 900, 600, 1200, 3600');
INSERT INTO `config_descriptions` VALUES ('Corpse.EmptyLootShow', 'If target can have loot (or can be skining after loot) but no loot generated still show loot window\nDefault: 1 (show)\n         0 (not show)');
INSERT INTO `config_descriptions` VALUES ('CreatureFamilyAssistanceDelay', 'Reaction time for creature assistance call\nDefault: 1500 (1.5s)');
INSERT INTO `config_descriptions` VALUES ('CreatureFamilyAssistanceRadius', 'Radius which creature will use to call assistance without moving\nDefault: 10\n         0   - off');
INSERT INTO `config_descriptions` VALUES ('CreatureFamilyFleeAssistanceRadius', 'Radius which creature will use to seek for a near creature for assistance. Creature will flee to this creature.\nDefault: 30\n         0   - off');
INSERT INTO `config_descriptions` VALUES ('CreatureFamilyFleeDelay', 'Time during which creature can flee when no assistant found\nDefault: 7000 (7s)');
INSERT INTO `config_descriptions` VALUES ('CreatureRespawnAggroDelay', 'The delay between when a creature spawns and when it can be aggroed by nearby movement.\nDefault: 5000 (5s)');
INSERT INTO `config_descriptions` VALUES ('CrossBattlegrounds.Enabled', 'Enable mixing teams into battlegrounds for faster queues.\r\nDefault: 0 (Disabled)\r\n         1 (Enabled)');
INSERT INTO `config_descriptions` VALUES ('DBC.Locale', 'DBC Language Settings\n0 = English; 1 = Korean; 2 = French; 3 = German; 4 = Chinese; 5 = Taiwanese; 6 = Spanish; 7 = Spanish Mexico\n8 = Russian; 255 = Auto Detect (Default)');
INSERT INTO `config_descriptions` VALUES ('Death.Bones.BattlegroundOrArena', 'Enabled/disabled creating bones instead corpse at resurrection (in normal zones/instacnes, or battleground/arenas)\nDefault: 1 (enabled)\n         0 (disabled)');
INSERT INTO `config_descriptions` VALUES ('Death.Bones.World', 'Enabled/disabled creating bones instead corpse at resurrection (in normal zones/instacnes, or battleground/arenas)\nDefault: 1 (enabled)\n         0 (disabled)');
INSERT INTO `config_descriptions` VALUES ('Death.CorpseReclaimDelay.PvE', 'Enabled/disabled increase corpse reclaim delay at often PvP/PvE deaths\nDefault: 1 (enabled)\n         0 (disabled)');
INSERT INTO `config_descriptions` VALUES ('Death.CorpseReclaimDelay.PvP', 'Enabled/disabled increase corpse reclaim delay at often PvP/PvE deaths\nDefault: 1 (enabled)\n         0 (disabled)');
INSERT INTO `config_descriptions` VALUES ('Death.Ghost.RunSpeed.Battleground', 'Modifies the speed of player\'s ghosts, removed upon reviving, not permanent/saved, in non-BG and BG maps\nDefault: 1.0 (normal speed)');
INSERT INTO `config_descriptions` VALUES ('Death.Ghost.RunSpeed.World', 'Modifies the speed of player\'s ghosts, removed upon reviving, not permanent/saved, in non-BG and BG maps\nDefault: 1.0 (normal speed)');
INSERT INTO `config_descriptions` VALUES ('Death.SicknessLevel', 'Starting Character start gain sickness at spirit resurrection (1 min)\nDefault: 11\n         -10 - character will have full time (10min) sickness at 1 level\n         maxplayerlevel+1 - character will not have sickness at any level');
INSERT INTO `config_descriptions` VALUES ('DeclinedNames', 'Allow russian clients to set and use declined names\nDefault: 0 - do not use declined names, except when the Russian RealmZone is set\n         1 - use declined names');
INSERT INTO `config_descriptions` VALUES ('DetectPosCollision', 'Check final move position, summon position, etc for visible collision with other objects or\nwall (wall only if vmaps are enabled)\nDefault: 1 (enable, requires more CPU power)\n         0 (disable, not so nice position selection but will require less CPU po');
INSERT INTO `config_descriptions` VALUES ('DurabilityLossChance.Absorb', 'Chance lost one from armor items durability point at damage absorb.\nDefault: 0.5 (100/0.5 = 200) Each 200 absorbs apply one from 15 possible armor equipped items');
INSERT INTO `config_descriptions` VALUES ('DurabilityLossChance.Block', 'Chance lost sheild durability point at damage block.\nDefault: 0.05 (100/0.05 = 2000) Each 2000 partly or full blocked attacks shield lost point');
INSERT INTO `config_descriptions` VALUES ('DurabilityLossChance.Damage', 'Chance lost one from equiped items durability point at damage apply or receive.\nDefault: 0.5 (100/0.5 = 200) Each 200 damage apply one from 19 possible equipped items');
INSERT INTO `config_descriptions` VALUES ('DurabilityLossChance.Parry', 'Chance lost weapon durability point at parry.\nDefault: 0.05 (100/0.05 = 2000) Each 2000 parry attacks main weapon lost point');
INSERT INTO `config_descriptions` VALUES ('Event.Announce', 'Announce game events\r\nDefault: 0 (false)\r\n         1 (true)');
INSERT INTO `config_descriptions` VALUES ('Expansion', 'Allow server use content from expansion\n         2 - check expansion 2 maps existence, and if client support expansion 2 and account have\n             expansion 2 setting then allow visit expansion 2 maps, allow create new class character)\nDefault: 1 - ch');
INSERT INTO `config_descriptions` VALUES ('GameType', 'Server realm style\n0 = NORMAL; 1 = PVP; 4 = NORMAL; 6 = RP; 8 = RPPVP\nalso custom type: 16 FFA_PVP (free for all pvp mode like arena PvP in all zones except rest\nactivated places and sanctuaries)');
INSERT INTO `config_descriptions` VALUES ('GM.AcceptTickets', 'Is GM accepting tickets from player by default or not.\nDefault: 2 (last save state)\n         0 (disable)\n         1 (enable)');
INSERT INTO `config_descriptions` VALUES ('GM.Chat', 'GM chat mode at login\nDefault: 2 (last save state)\n         0 (disable)\n         1 (enable)');
INSERT INTO `config_descriptions` VALUES ('GM.InGMList.Level', 'Max GM level showed in GM list (if visible) in non-GM state (.gm off)\n         0 (none)\n         1 (only moderators)\n         2 (only gamemasters)\nDefault: 3 (anyone)');
INSERT INTO `config_descriptions` VALUES ('GM.InvisibleAura', 'A spell that will be cast when a gm uses \".gm visible off\" (Must be aura spell)\nDefault: 37800 (50% Transparency)\n         0 (Disabled)');
INSERT INTO `config_descriptions` VALUES ('GM.InWhoList.Level', 'Max GM level showed in who list (if visible).\n         0 (only players)\n         1 (only moderators)\n         2 (only gamemasters)\nDefault: 3 (anyone)');
INSERT INTO `config_descriptions` VALUES ('GM.LoginState', 'GM mode at login\nDefault: 2 (last save state)\n         0 (disable)\n         1 (enable)');
INSERT INTO `config_descriptions` VALUES ('GM.LogTrade', 'Include GM trade and trade slot enchanting operations in GM log if it enable\nDefault: 1 (include)\n         0 (not include)');
INSERT INTO `config_descriptions` VALUES ('GM.LowerSecurity', 'Disallow a lower security member to interact with a higher one using commands\nDefault: 0 (disable)\n         1 (enable)');
INSERT INTO `config_descriptions` VALUES ('GM.StartLevel', 'GM starting level (1-255)\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('GM.Visible', 'GM visibility at login\nDefault: 2 (last save state)\n         0 (invisible)\n         1 (visible)');
INSERT INTO `config_descriptions` VALUES ('GM.WhisperingTo', 'Is GM accepting whispers from player by default or not.\nDefault: 2 (last save state)\n         0 (disable)\n         1 (enable)');
INSERT INTO `config_descriptions` VALUES ('GridCleanUpDelay', 'Grid clean up delay (in milliseconds)\nDefault: 300000 (5 min)');
INSERT INTO `config_descriptions` VALUES ('GridUnload', 'Unload grids (if you have lot memory you can disable it to speed up player move to new grids second time)\nDefault: 1 (unload grids)\n         0 (do not unload grids)');
INSERT INTO `config_descriptions` VALUES ('GuarderSight', 'Unknown, not in original mangosd.conf');
INSERT INTO `config_descriptions` VALUES ('GuidReserveSize.Creature', 'Amount guids reserved for .npc add/.gobject add directly after last used in DB static spawned creature/gameobject guid\nCommands .npc add/.gobject add can be used only for guids from this reserve and required server restart if all guids\nfrom reserve used b');
INSERT INTO `config_descriptions` VALUES ('GuidReserveSize.GameObject', 'Amount guids reserved for .npc add/.gobject add directly after last used in DB static spawned creature/gameobject guid\nCommands .npc add/.gobject add can be used only for guids from this reserve and required server restart if all guids\nfrom reserve used b');
INSERT INTO `config_descriptions` VALUES ('Guild.BankEventLogRecordsCount', 'Count of guild_bank event log records stored in guild_bank_eventlog table\nIncrease to store more guild_bank events in table - minimum is 25 (GUILD_BANK_MAX_LOGS) for each guild_bank tab\nUseful when you don\'t want old log events to be overwritten by new, b');
INSERT INTO `config_descriptions` VALUES ('Guild.EventLogRecordsCount', 'Count of guild event log records stored in guild_eventlog table\nIncrease to store more guild events in table, minimum is 100\nYou can set it to very high value to prevent oldest guild events to be rewritten by latest guild events - but it can slow down per');
INSERT INTO `config_descriptions` VALUES ('Instance.IgnoreLevel', 'Ignore level requirement to enter instance\nDefault: 0 (false)\n         1 (true)');
INSERT INTO `config_descriptions` VALUES ('Instance.IgnoreRaid', 'Ignore raid requirement to enter instance\nDefault: 0 (false)\n         1 (true)');
INSERT INTO `config_descriptions` VALUES ('Instance.ResetTimeHour', 'The hour of the day (0-23) when the global instance resets occur.\nDefault: 4');
INSERT INTO `config_descriptions` VALUES ('Instance.UnloadDelay', 'Unload the instance map from memory after some time if no players are inside.\nDefault: 1800000 (miliseconds, i.e 30 minutes)\n         0 (instance maps are kept in memory until they are reset)');
INSERT INTO `config_descriptions` VALUES ('InstantLogout', 'Enable or disable instant logout for security level (0..4) or high (NOT in combat/while dueling/while falling)\nDefault: 1 (Mods/GMs/Admins)');
INSERT INTO `config_descriptions` VALUES ('ListenRange.Say', 'Distance from player to listen text that creature (or other world object) say\nDefault: 40');
INSERT INTO `config_descriptions` VALUES ('ListenRange.TextEmote', 'Distance from player to listen textemote that creature (or other world object) say\nDefault: 40');
INSERT INTO `config_descriptions` VALUES ('ListenRange.Yell', 'Distance from player to listen text that creature (or other world object) yell\nDefault: 300');
INSERT INTO `config_descriptions` VALUES ('MailDeliveryDelay', 'Mail delivery delay time for item sending\nDefault: 3600 sec (1 hour)');
INSERT INTO `config_descriptions` VALUES ('MapUpdateInterval', 'Map update interval (in milliseconds)\nDefault: 100');
INSERT INTO `config_descriptions` VALUES ('MassMailer.SendPerTick', 'Max amount mail send each tick from mails list scheduled for mass mailer proccesing.\nMore mails increase server load but speedup mass mail proccess. Normal tick length: 50 msecs, so 20 ticks in sec and 200 mails in sec by default.\nDefault: 10');
INSERT INTO `config_descriptions` VALUES ('MaxArenaPoints', 'Max arena points that player can have.\nDefault: 5000');
INSERT INTO `config_descriptions` VALUES ('MaxCoreStuckTime', 'Periodically check if the process got freezed, if this is the case force crash after the specified\namount of seconds. Must be > 0. Recommended > 10 secs if you use this.\nDefault: 0 (Disabled)');
INSERT INTO `config_descriptions` VALUES ('MaxGroupXPDistance', 'Max distance to creature for group memeber to get XP at creature death.\nDefault: 74');
INSERT INTO `config_descriptions` VALUES ('MaxHonorPoints', 'Max honor points that player can have.\nDefault: 75000');
INSERT INTO `config_descriptions` VALUES ('MaxOverspeedPings', 'Maximum overspeed ping count before player kick (minimum is 2, 0 used to disable check)\nDefault: 2');
INSERT INTO `config_descriptions` VALUES ('MaxPlayerLevel', 'Max level that can be reached by a player for experience (in range from 1 to 100).\nChange not recommended\nDefault: 70');
INSERT INTO `config_descriptions` VALUES ('MaxPrimaryTradeSkill', 'Max count that player can learn the primary trade skill.\nDefault: 2\nMax : 10');
INSERT INTO `config_descriptions` VALUES ('MaxSpellCastsInChain', 'Max amount triggered spell casts in chain by one caster, prevent stack overflow crash\nToo Low value will make some correct triggered casts fail\n         0 (no limit)\nDefault: 20');
INSERT INTO `config_descriptions` VALUES ('MinCharterName', 'Minimal name length (1..24)\nDefault: 2');
INSERT INTO `config_descriptions` VALUES ('MinPetitionSigns', 'Min signatures count to creating guild (0..9).\nDefault: 9');
INSERT INTO `config_descriptions` VALUES ('MinPetName', 'Minimal name length (1..12)\nDefault: 2');
INSERT INTO `config_descriptions` VALUES ('MinPlayerName', 'Minimal name length (1..12)\nDefault: 2');
INSERT INTO `config_descriptions` VALUES ('mmap.enabled', 'Enable/Disable pathfinding using mmaps\nDefault: 1 (enable)\n         0 (disable)');
INSERT INTO `config_descriptions` VALUES ('mmap.ignoreMapIds', 'Disable mmap pathfinding on the listed maps.\nList of map ids with delimiter \',\'');
INSERT INTO `config_descriptions` VALUES ('MonsterSight', 'Unknown, not in original mangosd.conf');
INSERT INTO `config_descriptions` VALUES ('Motd', 'Message of the Day. Displayed at worldlogin for every user (\'@\' for a newline).');
INSERT INTO `config_descriptions` VALUES ('Network.KickOnBadPacket', 'Kick player on bad packet format.\nDefault: 0 - do not kick\n         1 - kick');
INSERT INTO `config_descriptions` VALUES ('Network.OutKBuff', 'The size of the output kernel buffer used ( SO_SNDBUF socket option, tcp manual ).\nDefault: -1 (Use system default setting)');
INSERT INTO `config_descriptions` VALUES ('Network.OutUBuff', 'Userspace buffer for output. This is amount of memory reserved per each connection.\nDefault: 65536');
INSERT INTO `config_descriptions` VALUES ('Network.TcpNodelay', 'TCP Nagle algorithm setting\nDefault: 0 (enable Nagle algorithm, less traffic, more latency)\n         1 (TCP_NO_DELAY, disable Nagle algorithm, more traffic but less latency)');
INSERT INTO `config_descriptions` VALUES ('Network.Threads', 'Number of threads for network, recommend 1 thread per 1000 connections.\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('OffhandCheckAtTalentsReset', 'Talent reset can change offhand weapon restrictions for equip slots.\nDefault: 0 - recheck offhand slot weapon only at zone update\n         1 - recheck offhand slot weapon at talent reset also');
INSERT INTO `config_descriptions` VALUES ('OutdoorPvp.EPEnabled', 'Enable Eastern Plaguelands Outdoor pvp');
INSERT INTO `config_descriptions` VALUES ('OutdoorPvp.HPEnabled', 'Enable Hellfire Peninsula Outdoor pvp');
INSERT INTO `config_descriptions` VALUES ('OutdoorPvp.NAEnabled', 'Enable Halaa (Nagrand) Outdoor pvp');
INSERT INTO `config_descriptions` VALUES ('OutdoorPvp.SIEnabled', 'Enable Silithus Outdoor pvp');
INSERT INTO `config_descriptions` VALUES ('OutdoorPvp.TFEnabled', 'Enable Terokkar Forest  Outdoor pvp');
INSERT INTO `config_descriptions` VALUES ('OutdoorPvp.ZMEnabled', 'Enable Zangarmarsh Outdoor pvp');
INSERT INTO `config_descriptions` VALUES ('PetUnsummonAtMount', 'Persmanent pet will unsummoned at player mount\n         0 - unsummon only for flying mounts\nDefault: 1 - unsummon for any mount');
INSERT INTO `config_descriptions` VALUES ('PlayerCommands', 'Should player chat be parsed for GM commands.\nDefault: 1 (parse commands)\n         0 (ignore commands)');
INSERT INTO `config_descriptions` VALUES ('PlayerLimit', 'Maximum number of players in the world. Excluding Mods, GM\'s and Admins\nDefault: 100\n         0 (for infinite players)\n        -1 (for Mods, GM\'s and Admins only)\n        -2 (for GM\'s and Admins only)\n        -3 (for Admins only)');
INSERT INTO `config_descriptions` VALUES ('PlayerSave.Interval', 'Player save interval (in milliseconds)\nDefault: 900000 (15 min)');
INSERT INTO `config_descriptions` VALUES ('PlayerSave.PerSecond', 'Player saves per second (only applied if PlayerSave.Interval = 0)\nDefault: 2 (0.5s between saves)');
INSERT INTO `config_descriptions` VALUES ('PlayerSave.Stats.MinLevel', 'Minimum level for saving character stats for external usage in database\nDefault: 0  (do not save character stats)\n         1+ (save stats for characters with level 1+)');
INSERT INTO `config_descriptions` VALUES ('PlayerSave.Stats.SaveOnlyOnLogout', 'Enable/Disable saving of character stats only on logout\nDefault: 1 (only save on logout)\n         0 (save on every player save)');
INSERT INTO `config_descriptions` VALUES ('ProcessPriority', 'Process priority setting (Used only at Windows)\nDefault: 1 (HIGH)\n         0 (Normal)');
INSERT INTO `config_descriptions` VALUES ('Quests.Daily.ResetHour', 'Hour when daily quests reset (0..23)\nDefault: 6');
INSERT INTO `config_descriptions` VALUES ('Quests.HighLevelHideDiff', 'Quest level difference to hide for player high level quests:\nif player_level < quest_min_level - HighLevelQuestsHideDiff then quest \"!\" mark not show for quest giver\nDefault: 7\n        -1 (show all available quests marks)');
INSERT INTO `config_descriptions` VALUES ('Quests.IgnoreRaid', 'Non-raid quests allowed in raids\nDefault: 0 (not allowed)\n         1 (allowed)');
INSERT INTO `config_descriptions` VALUES ('Quests.LowLevelHideDiff', 'Quest level difference to hide for player low level quests:\nif player_level > quest_level + LowLevelQuestsHideDiff then quest \"!\" mark not show for quest giver\nDefault: 4\n        -1 (show all available quests marks)');
INSERT INTO `config_descriptions` VALUES ('Ra.Enable', 'Enable remote console\nDefault: 0 - off\n         1 - on');
INSERT INTO `config_descriptions` VALUES ('RabbitDay', 'Set to Rabbit Day (date in unix time), only the day and month are considered, the year is not important\nDefault: 0 (off)\nSuggested: 954547200 (April 1st, 2000)');
INSERT INTO `config_descriptions` VALUES ('Rate.Auction.Cut', 'Auction rates (auction time, deposit get at auction start, auction cut from price at auction end)');
INSERT INTO `config_descriptions` VALUES ('Rate.Auction.Deposit', 'Auction rates (auction time, deposit get at auction start, auction cut from price at auction end)');
INSERT INTO `config_descriptions` VALUES ('Rate.Auction.Time', 'Auction rates (auction time, deposit get at auction start, auction cut from price at auction end)');
INSERT INTO `config_descriptions` VALUES ('Rate.Corpse.Decay.Looted', 'Controls how long the creature corpse stays after it had been looted, as a multiplier of its Corpse.Decay.* config.\nDefault: 0.0 (will use modifier /3 of the creatures spawntimesecs when 0.0)');
INSERT INTO `config_descriptions` VALUES ('Rate.Creature.Aggro', 'Aggro radius percent or off.\nDefault: 1   - 100%\n         1.5 - 150%\n         0   - off (0%)');
INSERT INTO `config_descriptions` VALUES ('Rate.Creature.Elite.Elite.Damage', 'Creature Damage Rates.\nExamples: 2 - creatures will damage 2x, 1.7 - 1.7x.');
INSERT INTO `config_descriptions` VALUES ('Rate.Creature.Elite.Elite.HP', 'Creature Health Ammount Modifier.\nExamples: 2 - creatures have 2x health, 1.7 - 1.7x.');
INSERT INTO `config_descriptions` VALUES ('Rate.Creature.Elite.Elite.SpellDamage', 'Creature Spell Damage Rates.\nExamples: 2 - creatures will damage with spells 2x, 1.7 - 1.7x.');
INSERT INTO `config_descriptions` VALUES ('Rate.Creature.Elite.RARE.Damage', 'Creature Damage Rates.\nExamples: 2 - creatures will damage 2x, 1.7 - 1.7x.');
INSERT INTO `config_descriptions` VALUES ('Rate.Creature.Elite.RARE.HP', 'Creature Health Ammount Modifier.\nExamples: 2 - creatures have 2x health, 1.7 - 1.7x.');
INSERT INTO `config_descriptions` VALUES ('Rate.Creature.Elite.RARE.SpellDamage', 'Creature Spell Damage Rates.\nExamples: 2 - creatures will damage with spells 2x, 1.7 - 1.7x.');
INSERT INTO `config_descriptions` VALUES ('Rate.Creature.Elite.RAREELITE.Damage', 'Creature Damage Rates.\nExamples: 2 - creatures will damage 2x, 1.7 - 1.7x.');
INSERT INTO `config_descriptions` VALUES ('Rate.Creature.Elite.RAREELITE.HP', 'Creature Health Ammount Modifier.\nExamples: 2 - creatures have 2x health, 1.7 - 1.7x.');
INSERT INTO `config_descriptions` VALUES ('Rate.Creature.Elite.RAREELITE.SpellDamage', 'Creature Spell Damage Rates.\nExamples: 2 - creatures will damage with spells 2x, 1.7 - 1.7x.');
INSERT INTO `config_descriptions` VALUES ('Rate.Creature.Elite.WORLDBOSS.Damage', 'Creature Damage Rates.\nExamples: 2 - creatures will damage 2x, 1.7 - 1.7x.');
INSERT INTO `config_descriptions` VALUES ('Rate.Creature.Elite.WORLDBOSS.HP', 'Creature Health Ammount Modifier.\nExamples: 2 - creatures have 2x health, 1.7 - 1.7x.');
INSERT INTO `config_descriptions` VALUES ('Rate.Creature.Elite.WORLDBOSS.SpellDamage', 'Creature Spell Damage Rates.\nExamples: 2 - creatures will damage with spells 2x, 1.7 - 1.7x.');
INSERT INTO `config_descriptions` VALUES ('Rate.Creature.Normal.Damage', 'Creature Damage Rates.\nExamples: 2 - creatures will damage 2x, 1.7 - 1.7x.');
INSERT INTO `config_descriptions` VALUES ('Rate.Creature.Normal.HP', 'Creature Health Ammount Modifier.\nExamples: 2 - creatures have 2x health, 1.7 - 1.7x.');
INSERT INTO `config_descriptions` VALUES ('Rate.Creature.Normal.SpellDamage', 'Creature Spell Damage Rates.\nExamples: 2 - creatures will damage with spells 2x, 1.7 - 1.7x.');
INSERT INTO `config_descriptions` VALUES ('Rate.Damage.Fall', 'Damage after fall rate. (1 - standard, 2 - double damage, 0.5 - half damage, etc)');
INSERT INTO `config_descriptions` VALUES ('Rate.Drop.Item.Artifact', 'Drop rates (items by quality and money)\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('Rate.Drop.Item.Epic', 'Drop rates (items by quality and money)\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('Rate.Drop.Item.Legendary', 'Drop rates (items by quality and money)\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('Rate.Drop.Item.Normal', 'Drop rates (items by quality and money)\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('Rate.Drop.Item.Poor', 'Drop rates (items by quality and money)\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('Rate.Drop.Item.Rare', 'Drop rates (items by quality and money)\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('Rate.Drop.Item.Referenced', 'Drop rates (items by quality and money)\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('Rate.Drop.Item.Uncommon', 'Drop rates (items by quality and money)\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('Rate.Drop.Money', 'Drop rates (items by quality and money)\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('Rate.Energy', 'Health and power regeneration and rage income from damage.\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('Rate.Focus', 'Health and power regeneration and rage income from damage.\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('Rate.Health', 'Health and power regeneration and rage income from damage.\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('Rate.Honor', 'Honor gain rate');
INSERT INTO `config_descriptions` VALUES ('Rate.InstanceResetTime', 'Multiplier for the number of days in between global raid/heroic instance resets.\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('Rate.Loyalty', 'Health and power regeneration and rage income from damage.\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('Rate.Mana', 'Health and power regeneration and rage income from damage.\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('Rate.Mining.Amount', 'Mining Rates (Mining.Amount changes minimum/maximum usetimes of a deposit,\nMining.Next changes chance to have next use of a deposit)');
INSERT INTO `config_descriptions` VALUES ('Rate.Mining.Next', 'Mining Rates (Mining.Amount changes minimum/maximum usetimes of a deposit,\nMining.Next changes chance to have next use of a deposit)');
INSERT INTO `config_descriptions` VALUES ('Rate.Rage.Income', 'Health and power regeneration and rage income from damage.\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('Rate.Rage.Loss', 'Health and power regeneration and rage income from damage.\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('Rate.Reputation.Gain', 'Reputation Gain rate\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('Rate.Reputation.LowLevel.Kill', 'Reputation Gain form low level kill (grey creture)\nDefault: 0.2');
INSERT INTO `config_descriptions` VALUES ('Rate.Reputation.LowLevel.Quest', 'Reputation Gain rate\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('Rate.Rest.InGame', 'Resting points grow rates (1 - normal, 2 - double rate, 0.5 - half rate, etc) from standard values');
INSERT INTO `config_descriptions` VALUES ('Rate.Rest.Offline.InTavernOrCity', 'Resting points grow rates (1 - normal, 2 - double rate, 0.5 - half rate, etc) from standard values');
INSERT INTO `config_descriptions` VALUES ('Rate.Rest.Offline.InWilderness', 'Resting points grow rates (1 - normal, 2 - double rate, 0.5 - half rate, etc) from standard values');
INSERT INTO `config_descriptions` VALUES ('Rate.Skill.Discovery', 'Skill Discovery Rates\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('Rate.Talent', 'Talent Point rates\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('Rate.XP.Explore', 'XP rates\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('Rate.XP.Kill', 'XP rates\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('Rate.XP.Quest', 'XP rates\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('RealmZone', 'Server realm zone (set allowed alphabet in character names/etc). See also Strict*Names options.\n\n    1 Development    - any language (Default)\n    2 United States  - extended-Latin\n    3 Oceanic        - extended-Latin\n    4 Latin America  - extended-Lati');
INSERT INTO `config_descriptions` VALUES ('SaveRespawnTimeImmediately', 'Save respawn time for creatures at death and for gameobjects at use/open\nDefault: 1 (save creature/gameobject respawn time without waiting grid unload)\n         0 (save creature/gameobject respawn time at grid unload)');
INSERT INTO `config_descriptions` VALUES ('SkillChance.Green', 'Skill chance values (0..100)\nDefault: 100-75-25-0');
INSERT INTO `config_descriptions` VALUES ('SkillChance.Grey', 'Skill chance values (0..100)\nDefault: 100-75-25-0');
INSERT INTO `config_descriptions` VALUES ('SkillChance.MiningSteps', 'For skinning and Mining chance decrease with skill level.\nDefault: 0  - no decrease\n         75 - in 2 times each 75 skill points');
INSERT INTO `config_descriptions` VALUES ('SkillChance.Orange', 'Skill chance values (0..100)\nDefault: 100-75-25-0');
INSERT INTO `config_descriptions` VALUES ('SkillChance.Prospecting', 'For prospecting skillup not possible by default, but can be allowed as custom setting\nDefault: 0 - no skilups\n         1 - skilups possible');
INSERT INTO `config_descriptions` VALUES ('SkillChance.SkinningSteps', 'For skinning and Mining chance decrease with skill level.\nDefault: 0  - no decrease\n         75 - in 2 times each 75 skill points');
INSERT INTO `config_descriptions` VALUES ('SkillChance.Yellow', 'Skill chance values (0..100)\nDefault: 100-75-25-0');
INSERT INTO `config_descriptions` VALUES ('SkillFail.Gain.Fishing', 'For fishing skill gain possible at fail also\nDefault: 0 (disabled)\n         1 (enabled)');
INSERT INTO `config_descriptions` VALUES ('SkillFail.Loot.Fishing', 'For fishing instead fail provided junk loot\nDefault: 0 (disabled)\n         1 (enabled)');
INSERT INTO `config_descriptions` VALUES ('SkillFail.Possible.FishingPool', 'For fishing pool impossible fail from low skill by default\nDefault: 1 (enabled)\n         0 (disabled)');
INSERT INTO `config_descriptions` VALUES ('SkillGain.Crafting', 'crafting/defense/gathering/weapon skills gain at skill grow (1,2,...)\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('SkillGain.Defense', 'crafting/defense/gathering/weapon skills gain at skill grow (1,2,...)\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('SkillGain.Gathering', 'crafting/defense/gathering/weapon skills gain at skill grow (1,2,...)\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('SkillGain.Weapon', 'crafting/defense/gathering/weapon skills gain at skill grow (1,2,...)\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('SkipCinematics', 'Disable in-game script movie at first character\'s login(allows to prevent buggy intro in case of custom start location coordinates)\nDefault: 0 - show intro for each new character\n         1 - show intro only for first character of selected race\n         2');
INSERT INTO `config_descriptions` VALUES ('SOAP.Enabled', 'Enable soap service\nDefault: 0 - off\n         1 - on');
INSERT INTO `config_descriptions` VALUES ('SOAP.IP', 'Bound SOAP service ip address, use 0.0.0.0 to access from everywhere\r\nDefault: 127.0.0.1');
INSERT INTO `config_descriptions` VALUES ('SOAP.Port', 'SOAP port\r\nDefault: 7878');
INSERT INTO `config_descriptions` VALUES ('StartArenaPoints', 'Amount of arena points that new players will start with\nDefault: 0');
INSERT INTO `config_descriptions` VALUES ('StartHonorPoints', 'Amount of honor that new players will start with\nDefault: 0');
INSERT INTO `config_descriptions` VALUES ('StartPlayerLevel', 'Staring level that have character at creating (in range 1 to MaxPlayerLevel)\nDefault: 1');
INSERT INTO `config_descriptions` VALUES ('StartPlayerMoney', 'Amount of money that new players will start with.\nIf you want to start with one silver, use for example 100 (100 copper = 1 silver)\nDefault: 0');
INSERT INTO `config_descriptions` VALUES ('StrictCharterNames', 'Limit guild/arena team charter names to language specific symbols set, not allow create charters with not allowed symbols in name\nDefault: 0 disable\n         1 basic latin characters  (strict)\n         2 realm zone specific (strict). See RealmZone setting');
INSERT INTO `config_descriptions` VALUES ('StrictPetNames', 'Limit pet names to language specific symbols set\nDefault: 0 disable\n         1 basic latin characters  (strict)\n         2 realm zone specific (strict). See RealmZone setting.\n           Note: In any case if you want correctly see character name at client');
INSERT INTO `config_descriptions` VALUES ('StrictPlayerNames', 'Limit player name to language specific symbols set, not allow create characters, and set rename request and disconnect at not allowed symbols name\nDefault: 0 disable (but limited server timezone dependent client check)\n         1 basic latin characters  (');
INSERT INTO `config_descriptions` VALUES ('TalentsInspecting', 'Allow other players see character talents in inspect dialog (Characters in Gamemaster mode can\ninspect talents always)\nDefault: 1 (allow)\n         0 (not allow)');
INSERT INTO `config_descriptions` VALUES ('TargetPosRecalculateRange', 'Max distance from movement target point (+moving unit size) and targeted object (+size)\nafter that new target movement point calculated. Max: melee attack range (5), min: contact range (0.5)\nMore distance let have better performence, less distance let hav');
INSERT INTO `config_descriptions` VALUES ('ThreatRadius', 'Radius for creature to evade after being pulled away from combat start point\nIf ThreatRadius is less than creature aggro radius then aggro radius will be used\nDefault: 100 yards');
INSERT INTO `config_descriptions` VALUES ('TimerBar.Breath.GMLevel', 'Disable/enable waterbreathing for security level (0..4) or high\nDefault: 4 (None)');
INSERT INTO `config_descriptions` VALUES ('TimerBar.Breath.Max', 'Disable/enable waterbreathing for security level (0..4) or high\nDefault: 4 (None)');
INSERT INTO `config_descriptions` VALUES ('TimerBar.Fatigue.GMLevel', 'Disable/enable fatigue for security level (0..4) or high\nDefault: 4 (None)');
INSERT INTO `config_descriptions` VALUES ('TimerBar.Fatigue.Max', 'Fatigue max timer value (in secs)\nDefault: 60 (1 minute)\n          0 (instant death)');
INSERT INTO `config_descriptions` VALUES ('TimerBar.Fire.GMLevel', 'Disable/enable lava fire damage for security level (0..4) or high\nDefault: 4 (None)');
INSERT INTO `config_descriptions` VALUES ('TimerBar.Fire.Max', 'Lava damage delay max timer value (in secs)\nDefault:  1\n          0 (instant in lava damage start)');
INSERT INTO `config_descriptions` VALUES ('TradeSkill.GMIgnore.Level', 'GM level starting from trade skill level requirement ignored.\nDefault: 4 (Console as noneone)');
INSERT INTO `config_descriptions` VALUES ('TradeSkill.GMIgnore.MaxPrimarySkillsCount', 'GM level starting from max primary skill count requirement ignored.\nDefault: 4 (Console as noneone)');
INSERT INTO `config_descriptions` VALUES ('TradeSkill.GMIgnore.Skill', 'GM level starting from trade skill skill requirement ignored.\nDefault: 4 (Console as noneone)');
INSERT INTO `config_descriptions` VALUES ('UpdateUptimeInterval', 'Update realm uptime period in minutes (for save data in \'uptime\' table). Must be > 0\nDefault: 10 (minutes)');
INSERT INTO `config_descriptions` VALUES ('Visibility.AIRelocationNotifyDelay', 'Delay time between creature AI reactions on nearby movements\nDefault: 1000 (milliseconds)');
INSERT INTO `config_descriptions` VALUES ('Visibility.Distance.BGArenas', 'Visibility distance for different ingame object in different maps.\nVisibility on continents on offy ~90 yards. In BG/Arenas ~180. For instances default ~120.\nMax limited by active player zone: ~ 333\nMin limit is max aggro radius (45) * Rate.Creature.Aggro');
INSERT INTO `config_descriptions` VALUES ('Visibility.Distance.Continents', 'Visibility distance for different ingame object in different maps.\nVisibility on continents on offy ~90 yards. In BG/Arenas ~180. For instances default ~120.\nMax limited by active player zone: ~ 333\nMin limit is max aggro radius (45) * Rate.Creature.Aggro');
INSERT INTO `config_descriptions` VALUES ('Visibility.Distance.Grey.Object', 'Visibility grey distance for dynobjects/gameobjects/corpses/creature bodies\nDefault: 10 (yards)');
INSERT INTO `config_descriptions` VALUES ('Visibility.Distance.Grey.Unit', 'Visibility grey distance for creatures/players (fast changing objects)\naddition to appropriate object type Visibility.Distance.* use in case visibility removing to\nobject (except corpse around distances) If D is distance and G is grey distance then object');
INSERT INTO `config_descriptions` VALUES ('Visibility.Distance.InFlight', 'Visible distance for player in flight\nMin limit is 0 (not show any objects)');
INSERT INTO `config_descriptions` VALUES ('Visibility.Distance.Instances', 'Visibility distance for different ingame object in different maps.\nVisibility on continents on offy ~90 yards. In BG/Arenas ~180. For instances default ~120.\nMax limited by active player zone: ~ 333\nMin limit is max aggro radius (45) * Rate.Creature.Aggro');
INSERT INTO `config_descriptions` VALUES ('Visibility.GroupMode', 'Group visibility modes\nDefault: 0 (standard setting: only members from same group can 100% auto detect invisible player)\n         1 (raid members 100% auto detect invisible player from same raid)\n         2 (players from same team can 100% auto detect inv');
INSERT INTO `config_descriptions` VALUES ('Visibility.RelocationLowerLimit', 'Object\'s visibility update called, when distance between current object\'s position and position,\nwhere visiblity was updated last time, reaches RelocationLoverLimit value\nDefault: 10 (yards)');
INSERT INTO `config_descriptions` VALUES ('vmap.enableHeight', 'Enable/Disable VMaps support for line of sight and height calculation\nYou need to extract the VMaps in order to enable those options\nDefault: 1 (enable)\n         0 (disable)');
INSERT INTO `config_descriptions` VALUES ('vmap.enableIndoorCheck', 'Enable/Disable VMap based indoor check to remove outdoor-only auras (mounts etc.).\nRequires VMaps enabled to work.\nDefault: 1 (Enabled)\n         0 (Disabled)');
INSERT INTO `config_descriptions` VALUES ('vmap.enableLOS', 'Enable/Disable VMaps support for line of sight and height calculation\nYou need to extract the VMaps in order to enable those options\nDefault: 1 (enable)\n         0 (disable)');
INSERT INTO `config_descriptions` VALUES ('vmap.ignoreSpellIds', 'These spells are ignored for LoS calculation\nList of ids with delimiter \',\'');
INSERT INTO `config_descriptions` VALUES ('Warden.BanLength', 'Undocumented');
INSERT INTO `config_descriptions` VALUES ('Warden.ClientCheckHoldOff', 'Undocumented');
INSERT INTO `config_descriptions` VALUES ('Warden.ClientResponseDelay', 'Undocumented');
INSERT INTO `config_descriptions` VALUES ('Warden.Enabled', 'Undocumented');
INSERT INTO `config_descriptions` VALUES ('Warden.Kick.Ban', 'Undocumented');
INSERT INTO `config_descriptions` VALUES ('Warden.NumChecks', 'Undocumented');
INSERT INTO `config_descriptions` VALUES ('WorldBossLevelDiff', 'Difference for boss dynamic level with target\nDefault: 3');
